# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteAppFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseStorage'
  pod 'GoogleSignIn'

  # Pods for NoteAppFirebase

end
